---
title: "C. Viridis tables"
date: today
execute: 
  echo: false
  message: false
  warning: false
format: docx
---

```{r}
library(tidyverse)
library(lubridate)
library(modelr)
library(fda)
library(nlme)
library(emmeans)
library(pander)
```

## $T_b$ tables

```{r}
load('data/fit-tb.RData')
```

### Main
```{r}
fit_emm <- emmeans(fit, specs = 'type')

group_means <- summary(fit_emm) |>
  tibble() |>
  rename(Group = type, 
         Estimate = emmean) |>
  mutate(CI = paste('(', round(lower.CL, 2), 
                          ', ', round(upper.CL, 2), ')')) |>
  dplyr::select(Group, Estimate, SE, CI)

contrasts <- pairs(fit_emm) |> 
  confint() |> 
  tibble() |>
  rename(Group = contrast, 
         Estimate = estimate) |>
  mutate(CI = paste('(', round(lower.CL, 2), 
                          ', ', round(upper.CL, 2), ')')) |>
  dplyr::select(Group, Estimate, SE, CI) 

bind_rows(group_means, contrasts) |>
  pander(caption = "Estimated marginal means and contrasts for body temperatures of pregnant (G) and non-pregnant (N) snakes.")
```


### Supplemental

```{r}
fit.anova <- anova(fit, type = 'sequential')[-1,] 
rownames(fit.anova) <- c('Group', 'Hour', 'Day', 'Group:Hour', 'Group:Day', 'Hour:Day', 'Group:Hour:Day')
pander(fit.anova)
```

## $T_e$ tables

```{r}
rm(list = ls())
load('data/fit-te-revised.RData')
```

### Main
```{r}
emmeans(fit, ~ location*treatment) |>
  as_tibble() |>
  rename(Location = location,
         Exposure = treatment,
         Estimate = emmean) |>
  mutate(CI = paste('(', round(lower.CL, 2), 
                          ', ', round(upper.CL, 2), ')')) |>
  dplyr::select(Location, Exposure, Estimate, SE, CI) |>
  pander()
```

```{r}
contr.location <- emmeans(fit, ~ location) |>
  pairs() |> confint() |>
  rename(Contrast = contrast,
         Estimate = estimate) |>
  mutate(CI = paste('(', round(lower.CL, 2), 
                          ', ', round(upper.CL, 2), ')')) |>
  dplyr::select(Contrast, Estimate, SE, CI)

contr.exposure <- emmeans(fit, ~ treatment) |>
  pairs() |> confint() |>
  rename(Contrast = contrast,
         Estimate = estimate) |>
  mutate(CI = paste('(', round(lower.CL, 2), 
                          ', ', round(upper.CL, 2), ')')) |>
  dplyr::select(Contrast, Estimate, SE, CI)

bind_rows(contr.location, contr.exposure) |>
  pander()
```

### Supplemental

```{r}
fit.anova <- anova(fit, type = 'sequential')[-1,] 
rownames(fit.anova) <- c('Location', 'Exposure',
                         'Hour', 'Day', 'Location:Exposure',
                         'Location:Hour', 'Exposure:Hour',
                         'Location:Day', 'Exposure:Day',
                         'Hour:Day', 'Location:Exposure:Hour',
                         'Location:Exposure:Day',
                         'Location:Hour:Day',
                         'Exposure:Hour:Day',
                         'Location:Exposure:Hour:Day')
pander(fit.anova)
```